import "./globals.css";
import Header from "@/components/Header/Header";

export const metadata = {
  title: "Your App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}