export const CATEGORIES = {
    "ai-services": {
    label: "AI Services",
    subcategories: [
      "Chatbots & Virtual Assistants",
      "AI Content Generation",
      "AI Image Generation & Art",
      "AI Video Generation",
      "Prompt Engineering",
      "AI Consulting & Strategy",
      "Machine Learning Models",
      "AI Voice & Speech",
      "AI Automation & Agents",
      "AI Data Analysis",
      "Custom AI Solutions",
      "AI Integration (APIs / Tools)",
    ],
  },
    
    
    "business-services": {
    label: "Business Services",
    subcategories: [
      "Business Consulting",
      "Business Plans",
      "Career Counseling",
      "CRM Management",
      "Customer Care",
      "E-Commerce Management",
      "ERP Management",
      "Event Management",
      "Financial Consulting",
      "HR Consulting",
      "Legal Consulting",
      "Management",
      "Market Research",
      "Presentations",
      "Project Management",
      "Sales",
      "Supply Chain Management",
      "Virtual Assistant",
    ],
  },
    
    
    "data-science": {
    label: "Data Science",
    subcategories: [
      "Consultation",
      "Data Analytics",
      "Data Engineering",
      "Data Entry",
      "Data Processing",
      "Data Visualization",
      "Machine Learning",
      "Data Cleaning",
      "Database Design",
      "Statistical Analysis",
      "Web Scraping",
      "Business Intelligence",
    ],
  },
    
    
    "digital-marketing": {
    label: "Digital Marketing",
    subcategories: [
      "Affiliate Marketing",
      "Display Advertising",
      "E-Commerce Marketing",
      "Email Marketing",
      "Guest Posting",
      "Influencer Marketing",
      "Local SEO",
      "Marketing Advice",
      "Marketing Strategy",
      "Mobile App Marketing",
      "Podcast Marketing",
      "Public Relations",
      "Search Engine Marketing (SEM)",
      "Search Engine Optimization (SEO)",
      "Social Media Advertising",
      "Social Media Community Management",
      "Social Media Marketing",
      "Text Message Marketing",
      "Video Marketing",
      "Web Analytics",
      "Web Traffic",
      "Content Marketing",
      "Conversion Rate Optimization (CRO)",
      "Brand Strategy",
    ],
  },
    
    
    "graphics-design": {
    label: "Graphics & Design",
    subcategories: [
      "2D Drawings",
      "3D Modeling & Rendering",
      "Album Cover Design",
      "Architecture & Interior Design",
      "Book Design",
      "Brand Style Guides",
      "Brochure Design",
      "Building Information Modeling",
      "Business Cards",
      "Cartoons & Comics",
      "Car Wraps",
      "Catalog Design",
      "Character Modeling",
      "Email Design",
      "Fashion Design",
      "Flyer Design",
      "Fonts & Typography",
      "Game Art",
      "Graphics for Streamers",
      "Icon Design",
      "Industrial & Product Design",
      "Illustration",
      "Image Editing",
      "Infographic Design",
      "Invitation Card Design",
      "Jewelry Design",
      "Landing Page Design",
      "Landscape Design",
      "Logo Design",
      "Menu Design",
      "NFT Art",
      "Packaging & Label Design",
      "Pattern Design",
      "Pattern Making",
      "Podcast Cover Art",
      "Portraits & Caricatures",
      "Presentation Design",
      "Signage Design",
      "Social Media Design",
      "Storyboards",
      "T-Shirts & Merchandise",
      "Trade Booth Design",
      "UX Design",
      "Vector Tracing",
      "Web Banners",
    ],
  },
    
    
    "music-audio": {
    label: "Music and Audio",
    subcategories: [
      "Audio Ads Production",
      "Audiobook Production",
      "Audio Editing",
      "Audio Logo & Sonic Branding",
      "Beat Making",
      "DJ Drops & Tags",
      "DJ Mixing",
      "Jingles & Intros",
      "Meditation Music",
      "Mixing & Mastering",
      "Music & Audio Advice",
      "Music Transcription",
      "Online Music Lessons",
      "Podcast Editing",
      "Producers & Composers",
      "Remixing & Mashups",
      "Session Musicians",
      "Singers & Vocalists",
      "Songwriters",
      "Sound Design",
      "Synth Presets",
      "Vocal Tuning",
      "Voice Over",
      "Podcast Production",
      "Foley & Sound Effects",
    ],
  },
    
    
    photography: {
    label: "Photography",
    subcategories: [
      "Portrait Photography",
      "Product Photography",
      "Real Estate Photography",
      "Event Photography",
      "Wedding Photography",
      "Fashion Photography",
      "Food Photography",
      "Nature / Landscape Photography",
      "Drone / Aerial Photography",
      "Photo Editing & Retouching",
      "Stock Photography",
      "Commercial / Advertising Photography",
    ],
  },
    
    
    "programming-tech": {
    label: "Programming & Tech",
    subcategories: [
      "Chatbots",
      "Convert Files",
      "Cybersecurity & Data Protection",
      "Desktop Applications",
      "Development for Streamers",
      "DevOps & Cloud",
      "E-Commerce Development",
      "Electronics Engineering",
      "Game Development",
      "Mobile Apps",
      "NFT Development",
      "Online Coding Lessons",
      "Support & IT",
      "User Testing",
      "Website Builders & CMS",
      "Website Development",
      "Web Programming",
      "WordPress",
      "API Development",
      "Bug Fixes",
      "Database Development",
      "QA & Testing",
    ],
  },
    
    
    "travel-lifestyle": {
    label: "Travel & Lifestyle",
    subcategories: [
      "eVisa Assistance",
      "Flight Ticketing",
      "Hotel Booking",
      "Travelling Packages",
      "Travel Planning",
      "Travel Consulting",
      "Life Coaching",
      "Health & Wellness Coaching",
      "Fitness Coaching",
      "Relationship Coaching",
      "Personal Development",
      "Career Coaching",
      "Nutrition Advice",
      "Mindfulness & Meditation",
    ],
  },
    
    
    "video-animation": {
    label: "Video & Animation",
    subcategories: [
      "3D Product Animation",
      "Animation for Kids",
      "Animated GIFs",
      "Animation for Streamers",
      "App & Website Previews",
      "Article to Video",
      "Book Trailers",
      "Campaign Videos",
      "Character Animation",
      "Corporate Videos",
      "Crowdfunding Videos",
      "E-Commerce Product Videos",
      "eLearning Video Production",
      "Filmed Video Production",
      "Game Trailers",
      "Intro & Outro Videos",
      "Live Action Explainers",
      "Logo Animation",
      "Meditation Videos",
      "Music Videos",
      "Narrative-Based Videos",
      "NFT Animation",
      "Screencasting Videos",
      "Slideshow Videos",
      "Social Media Videos",
      "Subtitles & Captions",
      "Unboxing Videos",
      "Video Ads & Commercials",
      "Video Advice",
      "Video Editing",
      "Videographers",
      "Video Templates Editing",
      "Visual Effects",
      "Web Animation",
      "Whiteboard & Animated Explainers",
      "Motion Graphics",
      "Short-Form Video (Reels / TikTok)",
    ],
  },
    
    
    "writing-translation": {
    label: "Writing & Translation",
    subcategories: [
      "Ad Copy",
      "Articles & Blog Posts",
      "Beta Reading",
      "Book & eBook Writing",
      "Book Editing",
      "Brand Voice & Tone",
      "Business Names & Slogans",
      "Case Studies",
      "Cover Letters",
      "Creative Writing",
      "eLearning Content Development",
      "Email Copy",
      "Grant Writing",
      "Job Descriptions",
      "Podcast Writing",
      "Product Descriptions",
      "Proofreading & Editing",
      "Research & Summaries",
      "Resume Writing",
      "Sales Copy",
      "Scriptwriting",
      "Social Media Copy",
      "Speechwriting",
      "Technical Writing",
      "Transcription",
      "Translation",
      "UX Writing",
      "Website Content",
      "White Papers",
    ],
  },
    
    
    miscellaneous: {
    label: "Miscellaneous (General)",
    subcategories: [
      "General",
      "Other Services",
      "Custom Requests",
      "Not Listed Elsewhere",
    ],
  },
  } as const;
  
  export type CategoryKey = keyof typeof CATEGORIES;